add updated_at to sync workflow api

diff --git a/web/.husky/pre-commit b/web/.husky/pre-commit
--- a/web/.husky/pre-commit
+++ b/web/.husky/pre-commit
@@ -31,14 +31,16 @@ if $api_modified; then
         pip install ruff
     fi
 
-    ruff check ./api
-    result=$?
+    ruff check ./api || status=$?
 
-    if [ $result -ne 0 ]; then
+    status=${status:-0}
+
+
+    if [ $status -ne 0 ]; then
+      echo "Ruff linter on api module error, exit code: $status"
       echo "Please run 'dev/reformat' to fix the fixable linting errors."
+      exit 1
     fi
-
-    exit $result
 fi
 
 if $web_modified; then
